apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer-staging
  # namespace: your-namespace
spec:
  acme:
    # Configure your email here...
    # ---
    email: user@example.com

    # Configure your server here...
    # ---
    # Letsencrypt Production
    # server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-staging-issuer-account-key
    solvers:
    # Configure DNS or HTTP Challenge here...
    # ---
    # DNS Challenge:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
        # Configure your DNS Provider here...
        # ---
        # cloudflare:
        #   email: your-email@address
        # API Key:
        #   apiKeySecretRef:
        #     name: cloudflare-api-key-secret
        #     key: api-key
        # - or -
        # API Token:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token-secret
        #     key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsNames:
      #   - 'your-domain'
      #   - '*.your-domain'

    # HTTP Challenge:
    #  - http01:
    #      ingress:
    #        class: traefik