apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'sealed-secrets'
spec:
  project: 'default'
  destination:
    name: ''
    namespace: 'kube-system'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'vendor/k3s-base/applications/charts/sealed-secrets'
    repoURL: '$GIT_URL'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true